#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 24000

// 如果使用 Duplex I2S 模式，请注释下面一行
// #define AUDIO_I2S_METHOD_SIMPLEX

#ifdef AUDIO_I2S_METHOD_SIMPLEX

// #define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_5
// #define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_4
// #define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_6
// #define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_7
// #define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_16
// #define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_15

//esp32c3 super mini
#define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_8
#define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_7
#define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_9
#define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_2
#define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_3
#define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_4

//esp32s3 super mini
// #define AUDIO_I2S_MIC_GPIO_WS   GPIO_NUM_2
// #define AUDIO_I2S_MIC_GPIO_SCK  GPIO_NUM_1
// #define AUDIO_I2S_MIC_GPIO_DIN  GPIO_NUM_3
// #define AUDIO_I2S_SPK_GPIO_DOUT GPIO_NUM_11
// #define AUDIO_I2S_SPK_GPIO_BCLK GPIO_NUM_12
// #define AUDIO_I2S_SPK_GPIO_LRCK GPIO_NUM_13

#else

#define AUDIO_CODEC_ES8311_ADDR ES8311_CODEC_DEFAULT_ADDR

#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_3
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_4

#define AUDIO_I2S_GPIO_WS GPIO_NUM_7
#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_5
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_9
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_8
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_6
#define AUDIO_CODEC_PA_PIN GPIO_NUM_NC

#endif

//esp32s3 super mini
#define BUILTIN_LED_GPIO        GPIO_NUM_NC
#define BOOT_BUTTON_GPIO        GPIO_NUM_NC
#define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

//esp32s3 super mini
// #define BUILTIN_LED_GPIO        GPIO_NUM_48
// #define BOOT_BUTTON_GPIO        GPIO_NUM_0
// #define TOUCH_BUTTON_GPIO       GPIO_NUM_NC
// #define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
// #define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

//esp32c3 super mini
#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_NC
#define DISPLAY_MOSI_PIN      GPIO_NUM_2
#define DISPLAY_CLK_PIN       GPIO_NUM_10
#define DISPLAY_DC_PIN        GPIO_NUM_1
#define DISPLAY_RST_PIN       GPIO_NUM_NC
#define DISPLAY_CS_PIN        GPIO_NUM_NC


//esp32s3 super mini
// #define DISPLAY_BACKLIGHT_PIN GPIO_NUM_8
// #define DISPLAY_MOSI_PIN      GPIO_NUM_4
// #define DISPLAY_CLK_PIN       GPIO_NUM_5
// #define DISPLAY_DC_PIN        GPIO_NUM_10
// #define DISPLAY_RST_PIN       GPIO_NUM_9
// #define DISPLAY_CS_PIN        GPIO_NUM_6

#define LCD_TYPE_ST7789_SERIAL
#define DISPLAY_WIDTH   128
#define DISPLAY_HEIGHT  128
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y true
#define DISPLAY_SWAP_XY false
#define DISPLAY_INVERT_COLOR  true
#define DISPLAY_RGB_ORDER  LCD_RGB_ELEMENT_ORDER_BGR
#define DISPLAY_OFFSET_X  2
#define DISPLAY_OFFSET_Y  3
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT true
#define DISPLAY_SPI_MODE 0

// A MCP Test: Control a lamp
#define LAMP_GPIO GPIO_NUM_18

#endif // _BOARD_CONFIG_H_
